adsec gh-1714 fix for missing ACI codes
arup-group/AdSec-Grasshopper pull request #95
Opened 2024-05-08 09:53 UTC by DominikaLos

2024-05-08 12:08 UTC, vilayatk approved these changes

2024-05-08 12:14 UTC, vilayatk requested changes
Waiting for tests to be added

2024-05-10 13:51 UTC, DominikaLos commented
> As discussed with Dominica, I'm waiting for tests to be added

ready to review

2024-05-10 13:51 UTC, DominikaLos commented on AdSecGH/AdSecGH.csproj
> +  <ItemGroup>
this is needed to make tests for internal objects

2024-05-20 06:03 UTC, vilayatk approved these changes

2024-05-20 06:20 UTC, SandeepArup approved these changes

2024-05-20 06:20 UTC, merged